language: java

sudo: required
dist: trusty

matrix:
  include:
  - jdk: oraclejdk8
    env: BUILD_JDK=ORACLE_JDK_8
  - jdk: oraclejdk11
    env: BUILD_JDK=ORACLE_JDK_11
  allow_failures:
  - env: BUILD_JDK=ORACLE_JDK_11

# https://docs.travis-ci.com/user/languages/java/#maven-dependency-management
install:
  - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V -DminimumPriority=1 -P dubbo-2.7.5
  - cd $TRAVIS_BUILD_DIR/sentinel-adapter/sentinel-apache-dubbo-adapter
  - mvn install -Dmaven.test.skip=true -Pdubbo-2.7.3
  - mvn install -Dmaven.test.skip=true -Pdubbo-2.7.6

after_success:
  - bash <(curl -s https://codecov.io/bash)

cache:
  directories:
  - $HOME/.m2/
